"use client";
import {useEffect,useState} from 'react';
import {RefreshCw,Search} from 'lucide-react';
type Entry={id:string;date:string;actor:string;action:string;recordId:string};
const labels:Record<string,string>={'contract.create':'Contrato cadastrado','contract.update':'Contrato alterado','contract.submit':'Enviado para OPEC','contract.approve':'Versão aprovada','contract.finalize':'Contrato homologado','contract.return':'Devolvido para correção','signature.client':'Cliente assinou','signature.speaker':'Locutor assinou','signature.renew':'Link renovado',receipt:'Recebimento',commission:'Repasse de comissão',reverseReceipt:'Estorno de recebimento',reverseCommission:'Estorno de comissão',delivery:'Inserção registrada'};
export function AuditLog(){
 const [items,setItems]=useState<Entry[]>([]),[next,setNext]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState('');
 async function load(cursor?:string){setBusy(true);try{const r=await fetch('/api/audit'+(cursor?'?cursor='+encodeURIComponent(cursor):''));const data=await r.json() as {error?:string;items:Entry[];next:string|null};if(!r.ok)throw Error(data.error);setItems(old=>cursor?[...old,...data.items]:data.items);setNext(data.next);setError('');}catch(e){setError(e instanceof Error?e.message:'Consulta indisponível');}finally{setBusy(false);}}
 useEffect(()=>{void load()},[]);
 const visible=items.filter(e=>`${e.actor} ${labels[e.action]||e.action} ${e.recordId}`.toLowerCase().includes(query.toLowerCase()));
 return <section aria-label="Auditoria"><div className="pro-toolbar"><label className="pro-search"><Search size={18}/><input aria-label="Buscar nos eventos carregados" placeholder="Buscar nos eventos carregados" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="icon-btn" title="Atualizar auditoria" aria-label="Atualizar auditoria" onClick={()=>load()} disabled={busy}><RefreshCw size={18}/></button></div>{error&&<p role="alert" className="pro-error">{error}</p>}<div className="audit-table"><table><thead><tr><th>Data</th><th>Responsável</th><th>Operação</th><th>Registro</th></tr></thead><tbody>{visible.map(e=><tr key={e.id}><td>{new Date(e.date).toLocaleString('pt-BR')}</td><td>{e.actor}</td><td>{labels[e.action]||e.action}</td><td>{e.recordId}</td></tr>)}</tbody></table></div>{!visible.length&&!busy&&<p className="pro-empty">Nenhum evento encontrado.</p>}{busy&&<p role="status">Consultando eventos...</p>}{next&&<button className="pro-outline" disabled={busy} onClick={()=>load(next)}>Carregar eventos anteriores</button>}</section>;
}
