"use client";
import {useEffect,useRef,useState} from "react";
import {Check,Download,Printer,Send,RefreshCw,Undo2} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {toast} from "sonner";
import {stages,type Contract} from "@/lib/domain";
import type {Operator} from "@/lib/operators";
import type {ContractVersion} from "@/lib/signing-domain";
import {clientSigner,formatAddress} from "@/lib/client-identity";
type Metadata=Omit<ContractVersion,"pdf"|"finalPdf">;
export function ContractWorkflow({c,operator,expected,related,disabled,onChanged}:{c:Contract;operator?:Operator;expected:string;related:{expectedClient?:string;expectedSpeaker?:string;expectedStation?:string};disabled:boolean;onChanged:()=>Promise<unknown>}){
 const [data,setData]=useState<{versions:Metadata[];invites:any[];whatsappConfigured:boolean}|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[reviewed,setReviewed]=useState(false),[returning,setReturning]=useState(false),[reason,setReason]=useState("");
 const latest=useRef({c,onChanged});latest.current={c,onChanged};
 useEffect(()=>{setReviewed(false)},[expected,related.expectedClient,related.expectedSpeaker,related.expectedStation]);
 const party=(raw?:string)=>{try{return JSON.parse(raw||'{}')}catch{return {}}};
 const client=party(related.expectedClient),speaker=party(related.expectedSpeaker),station=party(related.expectedStation);
 const signer=clientSigner({...client,document:client.document||"",name:client.name||"",contact:client.contact||"",phone:client.phone||""});
 async function read(signal?:AbortSignal){if(disabled)return;try{const r=await fetch('/api/workflow?contractId='+encodeURIComponent(c.id),{signal});const body:any=await r.json();if(!r.ok)throw Error(body.error);setData(body);setError('');if(body.current&&(body.current.stage!==latest.current.c.stage||body.current.workflowVersion!==latest.current.c.workflowVersion||body.current.status!==latest.current.c.status))await latest.current.onChanged();}catch(e:any){if(e.name!=='AbortError')setError(e.message);}}
 useEffect(()=>{const controller=new AbortController();read(controller.signal);const timer=setInterval(()=>read(controller.signal),20000);return()=>{controller.abort();clearInterval(timer)}},[c.id,c.stage,c.workflowVersion,disabled]);
 async function action(action:string){setBusy(true);try{const r=await fetch('/api/workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,contractId:c.id,expected,...related,confirmed:reviewed,reason})});const result:any=await r.json();if(!r.ok)throw Error(result.error);toast.success(action==='finalize'?'Contrato confirmado e liberado para veiculação':'Etapa registrada');setReturning(false);setReviewed(false);await onChanged();await read();}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 const opec=['admin','opec'].includes(operator?.role||''),agent=['admin','opec','agent'].includes(operator?.role||''),terminal=['Cancelado','Encerrado'].includes(c.status),blocked=busy||disabled||terminal;
 const current=data?.versions.find(v=>v.number===c.workflowVersion),invite=data?.invites.find(i=>i.versionId===current?.id&&!i.revokedAt&&!i.usedAt&&i.role===(c.stage===2?'client':'speaker'));
 const pdf=(v:Metadata,final=false,inline=false)=>'/api/workflow/document?versionId='+encodeURIComponent(v.id)+(final?'&final=1':'')+(inline?'&inline=1':'');
 return <div><ol className="flow-list" aria-label="Etapas do contrato">{stages.map((s,i)=><li key={s} aria-current={i===c.stage?'step':undefined} className={i<c.stage||c.stage===5?'done':i===c.stage?'current':''}><span>{i<c.stage||c.stage===5?<Check size={16}/>:i+1}</span><div><strong>{s}</strong><small>{i<c.stage||c.stage===5?'Etapa concluída':i===c.stage?'Etapa atual':'Aguardando etapa anterior'}</small></div></li>)}</ol>{error&&<p className="pro-error" role="alert">{error}</p>}{disabled&&<p className="pro-note">Demonstração: nenhuma assinatura ou mensagem será enviada.</p>}{!disabled&&data&&!data.whatsappConfigured&&<p className="pro-error">WhatsApp oficial não conectado. Links e códigos não serão enviados; as assinaturas permanecem pendentes.</p>}
 {c.stage===1&&<dl className="details-grid">{[["Responsável do anunciante",client.contact],["WhatsApp do cliente",client.phone],["Documento do anunciante",client.document],["Locutor/agente",speaker.name],["WhatsApp do locutor",speaker.phone],["CNPJ da emissora",station.document]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||"Não informado"}</dd></div>)}</dl>}{!terminal&&<div className="row-actions">{c.stage===0&&agent&&<button className="pro-primary" disabled={blocked} onClick={()=>action('submit')}><Send size={16}/>Enviar para OPEC</button>}{c.stage===1&&opec&&<div><label className="pro-note"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> Conferi anunciante, representante, WhatsApp, locutor, valores, parcelas e condições.</label><button className="pro-primary" disabled={blocked||!reviewed} onClick={()=>action('approve')}><Check size={16}/>Aprovar e solicitar assinatura do cliente</button></div>}{[2,3].includes(c.stage)&&<div><p className="pro-note">{c.stage===2?'Aguardando assinatura do cliente.':'Cliente assinou. Aguardando assinatura do locutor/agente.'} Nenhum aceite pode ser registrado pela administração.</p>{invite&&<p className="pro-note">{invite.notification==='accepted'?'Mensagem aceita pelo WhatsApp; entrega e leitura não confirmadas.':invite.notificationError||'Envio pendente.'} Link válido até {new Date(invite.expiresAt).toLocaleString('pt-BR')}.</p>}{opec&&<div className="row-actions"><button className="pro-outline" disabled={blocked||!data?.whatsappConfigured} onClick={()=>action('retry')}><Send size={16}/>Tentar envio pendente</button><button className="pro-outline" disabled={blocked} onClick={()=>action('renew')}><RefreshCw size={16}/>Renovar link</button></div>}</div>}{c.stage===4&&opec&&<button className="pro-primary" disabled={blocked||current?.signatures.length!==2} onClick={()=>action('finalize')}><Check size={16}/>Confirmar contrato e liberar veiculação</button>}{c.stage>0&&c.stage<5&&opec&&<button className="pro-outline" disabled={blocked} onClick={()=>setReturning(true)}><Undo2 size={16}/>Devolver para correção</button>}</div>}
 {c.stage===5&&!c.workflowVersion&&<p className="pro-note">Contrato anterior ao fluxo de assinatura externa. Os registros internos não são assinaturas eletrônicas.</p>}
 {c.stage===1&&<><dl className="details-grid">{[["Nome do signatário",signer.name],["CPF do signatário",signer.document],["WhatsApp para assinatura",signer.phone],["Endereço do anunciante",formatAddress(client)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||"Não informado"}</dd></div>)}</dl>{c.template&&<details className="template-preview"><summary>{c.template.name} · revisão {c.template.version}</summary><p>{c.template.clauses}</p><dl><dt>Cliente / representante</dt><dd>{c.template.clientSignatureLabel}</dd><dt>Locutor / agente</dt><dd>{c.template.speakerSignatureLabel}</dd><dt>Confirmação final</dt><dd>{c.template.opecSignatureLabel}</dd></dl></details>}</>}
 {data?.versions.map(v=><section key={v.id} className="detail-notes"><h3>Versão {v.number} · {({client:'Aguardando cliente',speaker:'Aguardando locutor',opec:'Aguardando OPEC',completed:'Concluída',superseded:'Substituída',cancelled:'Cancelada'})[v.state]}</h3><div className="row-actions"><a className="pro-outline compact" href={pdf(v)}><Download size={16}/>PDF apresentado</a>{v.state==='completed'&&<><a className="pro-primary compact" href={pdf(v,true)}><Download size={16}/>PDF concluído</a><a className="pro-outline compact" href={pdf(v,true,true)} target="_blank" rel="noreferrer"><Printer size={16}/>Abrir para impressão</a></>}</div><p className="pro-note" style={{overflowWrap:'anywhere'}}>PDF SHA-256: {v.finalHash||v.documentHash}</p>{v.signatures.map(s=><div className="history-row" key={s.id}><small>{s.role==='client'?'Cliente':'Locutor/agente'} · {new Date(s.date).toLocaleString('pt-BR')}</small><p>{s.name}<small style={{overflowWrap:'anywhere'}}>Registro SHA-256: {s.hash}</small></p></div>)}</section>)}
 <h3 className="history-title">Histórico do contrato</h3>{c.history.slice().reverse().map((h,i)=><div className="history-row" key={i}><small>{new Date(h.date).toLocaleString('pt-BR')}</small><p>{h.text}<small>{h.actor||'Registro anterior sem autoria'}</small></p></div>)}
 <Dialog open={returning} onOpenChange={setReturning}><DialogContent><DialogTitle>Devolver para correção</DialogTitle><DialogDescription>Os links pendentes serão revogados. Uma nova conferência e novas assinaturas serão necessárias após a correção.</DialogDescription><form className="pro-form" onSubmit={e=>{e.preventDefault();action('return')}}><label>Motivo<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={1000} required rows={4}/></label><button className="pro-primary" disabled={blocked||reason.trim().length<5}>Confirmar devolução</button></form></DialogContent></Dialog>
 </div>;
}
