"use client";
import {useEffect,useState} from "react";
import {Plus,Pencil,Save} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {toast} from "sonner";
import type {Operator,OperatorRole} from "@/lib/operators";
import type {Speaker} from "@/lib/domain";
const roles={admin:'Administrador',opec:'OPEC / Assistente administrativo',agent:'Locutor / Agente',finance:'Financeiro'};
export function OperatorSettings({speakers}:{speakers:Speaker[]}){
 const [list,setList]=useState<any[]>([]),[error,setError]=useState(''),[editing,setEditing]=useState<Operator|null>(null),[expected,setExpected]=useState<string|undefined>(),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/operators'),v:any=await r.json();if(!r.ok)throw Error(v.error);setList(v);setError('');}catch(e:any){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!editing)return;setBusy(true);try{const r=await fetch('/api/operators',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...editing,expected})}),v:any=await r.json();if(!r.ok)throw Error(v.error);toast.success('Permissão salva');setEditing(null);await load();}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 return <section><div className="pro-toolbar"><h2>Equipe e permissões</h2><button className="pro-outline" onClick={()=>{setExpected(undefined);setEditing({id:'',label:'',role:'opec',speakerId:'',active:true})}}><Plus size={16}/>Adicionar colaborador</button></div><p className="pro-note">O colaborador precisa primeiro receber acesso ao site privado. Ao abrir a administração, o código individual exibido na mensagem de acesso deve ser cadastrado abaixo. Esta permissão não envia convites de acesso ao site.</p>{error&&<p className="pro-error">{error}</p>}{list.map(item=>{const {recordId,...p}=item;return <div className="history-row" key={p.id}><small>{roles[p.role as OperatorRole]} · {p.active?'Ativo':'Inativo'}</small><p>{p.label}<small style={{overflowWrap:'anywhere'}}>{p.id}</small></p>{recordId!=='access:owner'&&<button className="icon-btn" title="Editar permissão" onClick={()=>{setExpected(JSON.stringify(p));setEditing(p)}}><Pencil size={16}/></button>}</div>})}<Dialog open={!!editing} onOpenChange={value=>{if(!value)setEditing(null)}}><DialogContent><DialogTitle>Permissão de colaborador</DialogTitle><DialogDescription>O perfil determina as operações permitidas na administração.</DialogDescription>{editing&&<form className="pro-form" onSubmit={save}><label>Código individual<input required value={editing.id} readOnly={!!expected} onChange={e=>setEditing({...editing,id:e.target.value})}/></label><label>Nome<input required maxLength={150} value={editing.label} onChange={e=>setEditing({...editing,label:e.target.value})}/></label><label>Perfil<Select value={editing.role} onValueChange={role=>setEditing({...editing,role:role as OperatorRole})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(roles).map(([id,label])=><SelectItem value={id} key={id}>{label}</SelectItem>)}</SelectContent></Select></label>{editing.role==='agent'&&<label>Locutor vinculado<Select value={editing.speakerId} onValueChange={speakerId=>setEditing({...editing,speakerId})}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{speakers.map(s=><SelectItem value={s.id} key={s.id}>{s.name}</SelectItem>)}</SelectContent></Select></label>}<label><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/> Acesso ativo</label><button className="pro-primary" disabled={busy||(editing.role==='agent'&&!editing.speakerId)}><Save size={16}/>Salvar permissão</button></form>}</DialogContent></Dialog></section>;
}
