import test from "node:test";
import assert from "node:assert/strict";
const base="http://127.0.0.1:5173";
const prefix=`qa-${Date.now()}`;
async function send(path,body){const r=await fetch(base+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};}
async function rows(){const r=await fetch(base+"/api/records");assert.equal(r.status,200);return r.json();}
test("Contrato, parcelas, recebimento parcial, comissão e controle de concorrência",async()=>{
 const client={id:prefix+"-client",name:"Anunciante de teste local",document:"",contact:"",email:"",phone:""};
 const speaker={id:prefix+"-speaker",name:"Locutor de teste local",email:"",phone:"",active:true};
 assert.equal((await send("/api/records",{kind:"client",data:client})).status,200);
 assert.equal((await send("/api/records",{kind:"speaker",data:speaker})).status,200);
 const c={id:prefix+"-contract",clientId:client.id,speakerId:speaker.id,title:"Campanha de teste local",start:"2026-10-01",end:"2026-10-31",amount:100,spots:10,duration:30,program:"Teste",status:"Rascunho",sector:"Varejo",commissionRate:30,manager:"Teste local"};
 assert.equal((await send("/api/records",{kind:"contract",data:c,billing:{count:3,first:"2026-01-31"}})).status,200);
 assert.equal((await send("/api/records",{kind:"contract",data:{...c,id:c.id+"-invalid",status:"Ativo"},billing:{count:1,first:"2026-10-06"}})).status,400);
 let data=await rows();let bill=data.find(r=>r.kind==="billing"&&r.data.contractId===c.id).data;
 assert.equal(bill.invoices.reduce((s,i)=>s+i.amountCents,0),10000);
 let editable=data.find(r=>r.data.id===c.id).data;
 assert.equal((await send("/api/records",{kind:"contract",data:{...editable,amount:101},previous:JSON.stringify(editable)})).status,200);
 data=await rows();bill=data.find(r=>r.data.id===bill.id).data;editable=data.find(r=>r.data.id===c.id).data;
 assert.equal(bill.invoices.reduce((s,i)=>s+i.amountCents,0),10100);
 assert.equal((await send("/api/records",{kind:"contract",data:{...editable,amount:100},previous:JSON.stringify(editable)})).status,200);
 data=await rows();bill=data.find(r=>r.data.id===bill.id).data;
 const expected=JSON.stringify(bill);
 const action={action:"receipt",contractId:c.id,invoiceId:bill.invoices[0].id,expected,amountCents:2500,date:"2026-10-06",method:"Pix",note:"Teste local"};
 assert.equal((await send("/api/actions",action)).status,200);
 assert.equal((await send("/api/actions",action)).status,409);
 data=await rows();bill=data.find(r=>r.data.id===bill.id).data;
 assert.equal(bill.invoices[0].payments[0].amountCents,2500);
 const repass={action:"commission",contractId:c.id,expected:JSON.stringify(bill),amountCents:751,date:"2026-10-06",method:"Pix",note:"Teste local"};
 assert.equal((await send("/api/actions",repass)).status,400);
 assert.equal((await send("/api/actions",{...repass,amountCents:750})).status,200);
 const current=data.find(r=>r.kind==="contract"&&r.data.id===c.id).data;
 assert.equal((await send("/api/records",{kind:"contract",data:{...current,amount:101},previous:JSON.stringify(current)})).status,400);
 let raw=current;
 assert.equal((await send("/api/actions",{action:"advance",contractId:c.id,expected:JSON.stringify(raw)})).status,400);
 assert.equal((await send("/api/workflow",{action:"submit",contractId:c.id,expected:JSON.stringify(raw)})).status,200);
 raw=(await rows()).find(r=>r.data.id===c.id).data;
 assert.equal(raw.stage,1);assert.ok(raw.history.every(h=>h.actor));
 assert.equal((await send("/api/records",{kind:"contract",data:{...raw,status:"Cancelado"},previous:JSON.stringify(raw)})).status,400);
 assert.equal((await send("/api/records",{kind:"contract",data:{...raw,status:"Cancelado",cancelReason:"Pedido do anunciante"},previous:JSON.stringify(raw)})).status,200);
 data=await rows();bill=data.find(r=>r.data.id===bill.id).data;
 const reverse={contractId:c.id,expected:JSON.stringify(bill),date:"2026-10-06",note:"Correção de lançamento"};
 assert.equal((await send("/api/actions",{...reverse,action:"reverseReceipt",paymentId:bill.invoices[0].payments[0].id})).status,400);
 assert.equal((await send("/api/actions",{...reverse,action:"reverseCommission",paymentId:bill.commissionPayments[0].id})).status,200);
 data=await rows();bill=data.find(r=>r.data.id===bill.id).data;
 assert.equal((await send("/api/actions",{...reverse,expected:JSON.stringify(bill),action:"reverseReceipt",paymentId:bill.invoices[0].payments[0].id})).status,200);
 data=await rows();bill=data.find(r=>r.data.id===bill.id).data;
 assert.equal((await send("/api/actions",{...action,expected:JSON.stringify(bill)})).status,200);
 raw=(await rows()).find(r=>r.data.id===c.id).data;
 assert.equal((await send("/api/actions",{action:"advance",contractId:c.id,expected:JSON.stringify(raw)})).status,400);
 const all=await rows();assert.ok(all.every(r=>r.kind!=="audit"));
 const backupResponse=await fetch(base+"/api/backup");assert.equal(backupResponse.status,200);
 const backup=await backupResponse.json();assert.equal(backup.format,"radioadmin-backup");
 const events=backup.records.filter(r=>r.kind==="audit"&&r.data.recordId===c.id);
 assert.ok(events.some(r=>r.data.action==="reverseReceipt"));assert.ok(events.every(r=>r.data.actorId));
 const editEvent=events.find(r=>r.data.action==="contract.update"&&r.data.before.contract);assert.equal(editEvent.data.after.contract.history.length,editEvent.data.before.contract.history.length+1);
 const crossOrigin=await fetch(base+"/api/records",{method:"POST",headers:{"Content-Type":"application/json",Origin:"https://untrusted.example"},body:JSON.stringify({kind:"client",data:client})});assert.ok([400,403].includes(crossOrigin.status));
 console.log(`Local fixture prefix: ${prefix}`);
});
