import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {Miniflare} from 'miniflare';
import {mkdir,writeFile} from 'node:fs/promises';
import {sha256,hmac,decryptToken,encryptToken,randomToken} from './signing-crypto.ts';
import {checkInvite,validCpf,phoneNumber} from './signing-domain.ts';
import {rehearseBackup} from '../scripts/rehearse-backup.mjs';
const secret='isolated-test-secret-not-a-production-key';
test('Tokens criptografados, CPF, telefone e expiração',async()=>{
 const token=randomToken();assert.equal(token.length,64);assert.equal(await decryptToken(secret,await encryptToken(secret,token)),token);
 assert.equal(validCpf('529.982.247-25'),true);assert.equal(validCpf('111.111.111-11'),false);assert.equal(validCpf('52998224724'),false);assert.equal(phoneNumber('(11) 99999-1234'),'5511999991234');assert.throws(()=>phoneNumber('123'));
 const c={workflowVersion:1,stage:2,status:'Rascunho'},v={number:1,state:'client'},i={role:'client',expiresAt:new Date(Date.now()+60000).toISOString()};checkInvite(c,v,i);assert.throws(()=>checkInvite(c,v,{...i,revokedAt:'now'}));assert.throws(()=>checkInvite(c,v,{...i,expiresAt:'2000-01-01'}));assert.throws(()=>checkInvite({...c,workflowVersion:2},v,i));assert.throws(()=>checkInvite(c,v,{...i,role:'speaker'}));
});
test('Fluxo completo isolado: perfis, versão, cliente, locutor, OPEC e PDF',async()=>{
 const bundle=await build({entryPoints:['lib/workflow-test-worker.ts'],bundle:true,write:false,format:'esm',platform:'browser',target:'es2022',external:['cloudflare:workers'],define:{'import.meta.env.DEV':'false'},logLevel:'silent'});
 const codes=new Map(),links=[];
 const options={modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'test-database'},bindings:{SIGNING_BRIDGE_SECRET:secret,SIGNING_ORIGIN:'https://signing.example',WHATSAPP_TOKEN:'test-only',WHATSAPP_PHONE_ID:'123',WHATSAPP_API_VERSION:'v25.0',WHATSAPP_SIGN_TEMPLATE:'test_link',WHATSAPP_OTP_TEMPLATE:'test_otp'},outboundService:async request=>{assert.equal(new URL(request.url).hostname,'graph.facebook.com');const body=await request.json();if(body.template.name==='test_otp')codes.set(body.to,body.template.components[0].parameters[0].text);else links.push(body);return Response.json({messages:[{id:'isolated-test-message'}]});}};const mf=new Miniflare(options);
 try{
 let db=await mf.getD1Database('DB');await db.prepare('CREATE TABLE records(id TEXT PRIMARY KEY,kind TEXT NOT NULL,data TEXT NOT NULL)').run();
 async function request(path,body,actor='owner'){const headers={'Content-Type':'application/json'};if(actor){headers['oai-authenticated-user-id']=actor;headers['oai-authenticated-user-email']=actor+'@example.test';}const r=await mf.dispatchFetch('https://admin.example'+path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};}
 async function read(id){const row=await db.prepare('SELECT data FROM records WHERE id=?').bind(id).first();return JSON.parse(row.data);}
 async function workflow(action,c,extra={},actor='owner'){return request('/api/workflow',{action,contractId:c.id,expected:JSON.stringify(c),...extra},actor);}
 async function invitation(c,role){const rows=await db.prepare("SELECT data FROM records WHERE kind='invite'").all();const i=rows.results.map(r=>JSON.parse(r.data)).find(i=>i.versionId==='version:'+c.id+':'+c.workflowVersion&&i.role===role&&!i.revokedAt);return {i,token:await decryptToken(secret,i.encryptedToken)};}
 async function bridge(op,token,extra={}){const raw=JSON.stringify({op,token,...extra}),timestamp=String(Date.now()),nonce=crypto.randomUUID();const r=await mf.dispatchFetch('https://admin.example/api/signing-bridge',{method:'POST',headers:{'Content-Type':'application/json','x-radioadmin-timestamp':timestamp,'x-radioadmin-nonce':nonce,'x-radioadmin-signature':await hmac(secret,timestamp+'.'+nonce+'.'+raw)},body:raw});return {status:r.status,body:await r.json()};}
 assert.equal((await request('/api/records',undefined,null)).status,401);
 assert.equal((await request('/api/records')).status,200);
 const client={id:'client-test',name:'Anunciante fictício',personType:'PJ',document:'11.222.333/0001-81',contact:'Representante fictício',representativeCpf:'52998224725',representativePhone:'11999991234',addressFields:{postalCode:'64460-000',street:'Rua de teste',number:'10',complement:'',neighborhood:'Centro',city:'Água Branca',state:'PI'},phone:'11999991111',email:''},speaker={id:'speaker-test',name:'Locutor de teste',document:'52998224725',addressFields:{postalCode:'64460-000',street:'Rua de teste',number:'20',complement:'',neighborhood:'Centro',city:'Água Branca',state:'PI'},phone:'11999995678',email:'',active:true},station={id:'station',name:'Emissora de teste',document:'12.345.678/0001-90',dial:'100.1 FM',address:'Endereço de teste',phone:'',email:''};
 for(const [kind,data] of [['speaker',speaker],['station',station]])assert.equal((await request('/api/records',{kind,data})).status,200);
 assert.equal((await read(speaker.id)).addressFields.postalCode,'64460000');
 assert.equal((await read(speaker.id)).document,speaker.document);
 for(const invalid of [{document:'11111111111'},{addressFields:undefined},{phone:'123'},{addressFields:{...speaker.addressFields,state:'XX'}}])assert.equal((await request('/api/records',{kind:'speaker',data:{...speaker,...invalid,id:crypto.randomUUID()}})).status,400);
 const savedSpeaker=await read(speaker.id);
 assert.equal((await request('/api/records',{kind:'speaker',data:{...savedSpeaker,stageName:' Voz da rádio ',addressFields:{...savedSpeaker.addressFields,complement:'Estúdio 2'}},previous:JSON.stringify(savedSpeaker)})).status,200);
 assert.equal((await read(speaker.id)).stageName,'Voz da rádio');
 assert.equal((await read(speaker.id)).addressFields.complement,'Estúdio 2');
 for(const [id,role] of [['opec','opec'],['agent','agent'],['finance','finance']])assert.equal((await request('/api/operators',{id,label:id,role,speakerId:speaker.id,active:true})).status,200);
 assert.equal((await request('/api/records',{kind:'client',data:{...client,creatorId:'forged'}},'agent')).status,200);
 assert.equal((await read(client.id)).creatorId,'agent');
 assert.equal((await read(client.id)).addressFields.postalCode,'64460000');assert.equal((await read(client.id)).addressFields.city,'Água Branca');assert.equal((await read(client.id)).address,undefined);
 assert.equal((await request('/api/records',{kind:'client',data:{...client,id:'invalid-address',addressFields:undefined,address:'Endereço único não estruturado'}})).status,400);
 assert.equal((await request('/api/records',{kind:'client',data:{...client,id:'invalid-cep',addressFields:{...client.addressFields,postalCode:'123'}}})).status,400);
 const other={...client,id:'other-client',name:'Outro anunciante'};
 assert.equal((await request('/api/records',{kind:'client',data:other})).status,200);
 const template={id:'template:test',name:'Modelo comercial de teste',clauses:'CLÁUSULA 1 - Objeto da veiculação.\n\nCLÁUSULA 2 - Pagamento conforme parcelas do contrato.',active:true,clientSignatureLabel:'Contratante',speakerSignatureLabel:'Agente comercial',opecSignatureLabel:'Homologação administrativa'};
 assert.equal((await request('/api/records',{kind:'template',data:template},'agent')).status,400);
 assert.equal((await request('/api/records',{kind:'template',data:{...template,version:99}})).status,200);
 assert.equal((await read(template.id)).version,1);
 assert.equal((await request('/api/records',{kind:'template',data:{...template,id:'invalid-template',clauses:'Condição com {{campo.inexistente}}.'}})).status,400);
 assert.equal((await request('/api/records',{kind:'client',data:{...other,id:'invalid-company',representativeCpf:'11111111111'}})).status,400);
 assert.equal((await request('/api/records',{kind:'client',data:{...other,id:'invalid-type',personType:'PF'}})).status,400);
 const ownRows=await request('/api/records',undefined,'agent');assert.ok(!ownRows.body.some(r=>r.data.id===other.id));
 assert.equal((await request('/api/records',{kind:'client',data:{...await read(other.id),phone:'11988888888'},previous:JSON.stringify(await read(other.id))},'agent')).status,400);
 let c={id:'contract-test',clientId:client.id,speakerId:speaker.id,title:'Campanha de teste isolado',start:'2026-10-01',end:'2026-10-31',amount:100,spots:10,duration:30,program:'Programa de teste',status:'Rascunho',sector:'Varejo',commissionRate:30,manager:'Agente de teste'};
 assert.equal((await request('/api/records',{kind:'contract',data:{...c,template:{...template,version:100,clauses:'Forged clauses must not be stored'}},templateSelection:{id:template.id,version:1},billing:{count:3,first:'2026-10-06'}},'agent')).status,200);c=await read(c.id);
 assert.equal(c.template.version,1);assert.equal(c.template.clauses,template.clauses);
 const savedTemplate=await read(template.id);
 assert.equal((await request('/api/records',{kind:'template',data:{...savedTemplate,clauses:'CLÁUSULA REVISADA - Novas condições não alteram contratos anteriores.'},previous:JSON.stringify(savedTemplate)},'opec')).status,200);
 assert.equal((await read(template.id)).version,2);assert.equal((await read(c.id)).template.clauses,template.clauses);
 assert.equal(c.creatorId,'agent');assert.equal((await workflow('submit',c,{},'agent')).status,200);c=await read(c.id);
 assert.equal((await request('/api/records',{kind:'client',data:{...await read(client.id),phone:'11988888888'},previous:JSON.stringify(await read(client.id))},'agent')).status,400);
 const draftBill=await read('billing:'+c.id);
 assert.equal((await request('/api/actions',{action:'receipt',contractId:c.id,expected:JSON.stringify(draftBill),invoiceId:draftBill.invoices[0].id,amountCents:100,date:'2026-10-01',method:'Pix'},'finance')).status,200);
 assert.equal((await request('/api/actions',{action:'commission',contractId:c.id,expected:JSON.stringify(await read(draftBill.id)),amountCents:30,date:'2026-10-01',method:'Pix'},'finance')).status,400);
 assert.equal((await workflow('approve',c,{confirmed:true},'agent')).status,400);assert.equal((await workflow('submit',c,{},'finance')).status,400);
 assert.equal((await request('/api/actions',{action:'advance',contractId:c.id,expected:JSON.stringify(c)})).status,400);
 assert.equal((await request('/api/records',{kind:'contract',data:{...c,title:'Alterado'},previous:JSON.stringify(c)},'agent')).status,400);
 assert.equal((await request('/api/records',{kind:'contract',data:c,templateSelection:{id:template.id,version:2},previous:JSON.stringify(c)},'agent')).status,400);
 const confirm={confirmed:true,expectedClient:JSON.stringify(await read(client.id)),expectedSpeaker:JSON.stringify(await read(speaker.id)),expectedStation:JSON.stringify(await read('station'))};
 assert.equal((await workflow('approve',c,confirm,'opec')).status,200);c=await read(c.id);assert.equal(c.stage,2);assert.equal(c.workflowVersion,1);assert.equal(links.length,1);
 assert.equal((await workflow('finalize',c,{},'opec')).status,400);
 const first=await invitation(c,'client');const view=await bridge('view',first.token);assert.equal(view.status,200);assert.equal(view.body.signatures.length,0);
 assert.equal(first.i.phone,'5511999991234');assert.equal(first.i.name,client.contact);
 assert.equal((await request('/api/signing-bridge',{op:'view',token:first.token})).status,403);
 assert.equal((await bridge('otp',first.token)).status,200);assert.equal((await bridge('otp',first.token)).status,400);
 const sign={name:'Representante fictício',document:'52998224725',code:codes.get(first.i.phone),consent:true,versionHash:view.body.versionHash,documentHash:view.body.documentHash,ip:'192.0.2.1',userAgent:'Isolated test'};
 assert.equal((await bridge('sign',first.token,{...sign,documentHash:'wrong'})).status,400);
 assert.equal((await bridge('sign',first.token,{...sign,document:'11144477735'})).status,400);
 assert.equal((await bridge('sign',first.token,{...sign,name:'Pessoa diferente'})).status,400);
 const parallel=await Promise.all([bridge('sign',first.token,sign),bridge('sign',first.token,sign)]);assert.equal(parallel.filter(r=>r.status===200).length,1);c=await read(c.id);assert.equal(c.stage,3);assert.equal(links.length,2);
 assert.equal((await bridge('sign',first.token,sign)).status,400);
 assert.equal((await workflow('return',c,{reason:'Corrigir condição comercial'},'opec')).status,200);c=await read(c.id);assert.equal(c.stage,0);const old=await read('version:'+c.id+':1');assert.equal(old.state,'superseded');assert.equal(old.signatures.length,1);assert.equal((await bridge('view',first.token)).status,400);
 assert.equal((await request('/api/records',{kind:'contract',data:{...c,notes:'Condição revisada'},previous:JSON.stringify(c)},'agent')).status,200);c=await read(c.id);
 assert.equal((await workflow('submit',c,{},'agent')).status,200);c=await read(c.id);assert.equal((await workflow('approve',c,confirm,'opec')).status,200);c=await read(c.id);assert.equal(c.workflowVersion,2);
 let active=await invitation(c,'client'),info=await bridge('view',active.token);await bridge('otp',active.token);
 assert.equal((await bridge('sign',active.token,{...sign,code:codes.get(active.i.phone),versionHash:info.body.versionHash,documentHash:info.body.documentHash})).status,200);c=await read(c.id);active=await invitation(c,'speaker');info=await bridge('view',active.token);await bridge('otp',active.token);
 for(let attempt=0;attempt<5;attempt++)assert.equal((await bridge('sign',active.token,{...sign,code:codes.get(active.i.phone)==='000000'?'111111':'000000',versionHash:info.body.versionHash,documentHash:info.body.documentHash})).status,400);
 assert.equal((await bridge('sign',active.token,{...sign,code:codes.get(active.i.phone),versionHash:info.body.versionHash,documentHash:info.body.documentHash})).status,400);
 assert.equal((await workflow('renew',c,{},'opec')).status,200);c=await read(c.id);active=await invitation(c,'speaker');info=await bridge('view',active.token);assert.equal((await bridge('otp',active.token)).status,200);
 assert.equal((await bridge('sign',active.token,{...sign,name:'Locutor fictício',code:codes.get(active.i.phone),versionHash:info.body.versionHash,documentHash:info.body.documentHash})).status,200);c=await read(c.id);assert.equal(c.stage,4);assert.equal((await workflow('finalize',c,{},'finance')).status,400);assert.equal((await workflow('finalize',c,{},'opec')).status,200);c=await read(c.id);assert.equal(c.stage,5);assert.equal(c.status,'Ativo');
 const failed={...sign,name:'Locutor fictício',code:'000000',versionHash:info.body.versionHash,documentHash:info.body.documentHash};
 const final=await read('version:'+c.id+':2');assert.equal(final.signatures.length,2);assert.equal(final.documentHash,info.body.documentHash);assert.equal(await sha256(Uint8Array.from(atob(final.finalPdf),c=>c.charCodeAt(0))),final.finalHash);
 const finalInvite=await read(active.i.id);assert.ok(new Date(finalInvite.expiresAt)>new Date(Date.now()+29*86400000));
 assert.equal((await bridge('document',active.token)).status,200);
 assert.equal((await request('/api/audit',undefined,'agent')).status,400);
 const audit=await request('/api/audit');assert.equal(audit.status,200);assert.ok(audit.body.items.some(e=>e.action==='contract.finalize'));assert.ok(audit.body.items.every(e=>!('before' in e)&&!('after' in e)));
 await mkdir('work/qa',{recursive:true});await writeFile('work/qa/contract-signed-test.pdf',Buffer.from(final.finalPdf,'base64'));
 assert.equal((await workflow('finalize',c,{},'opec')).status,400);const oldAgain=await read(old.id);assert.equal(oldAgain.pdf,old.pdf);assert.equal(oldAgain.documentHash,old.documentHash);
 assert.equal((await request('/api/actions',{action:'delivery',contractId:c.id,expected:JSON.stringify(c)},'agent')).status,400);assert.equal((await request('/api/actions',{action:'delivery',contractId:c.id,expected:JSON.stringify(c)},'opec')).status,200);
 const visible=await request('/api/records',undefined,'agent');assert.ok(visible.body.every(r=>['client','speaker','contract','billing','station','template'].includes(r.kind)));assert.equal((await request('/api/records',undefined,'unknown')).status,400);
 const document=await mf.dispatchFetch('https://admin.example/api/workflow/document?versionId='+encodeURIComponent(final.id)+'&final=1',{headers:{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.test'}});assert.equal(document.status,200);assert.equal(document.headers.get('content-type'),'application/pdf');
 await mf.setOptions({...options,bindings:{SIGNING_BRIDGE_SECRET:secret,SIGNING_ORIGIN:'https://signing.example'}});db=await mf.getD1Database('DB');
 const pending={...c,id:'pending-test',title:'Pending setup',status:'Rascunho',stage:0};assert.equal((await request('/api/records',{kind:'contract',data:pending,billing:{count:1,first:'2026-10-06'}},'agent')).status,200);let pc=await read(pending.id);await workflow('submit',pc,{},'agent');pc=await read(pc.id);assert.equal((await workflow('approve',pc,confirm,'opec')).status,200);pc=await read(pc.id);const pi=await invitation(pc,'client');assert.equal(pi.i.notification,'pending');assert.equal((await bridge('view',pi.token)).body.whatsappConfigured,false);assert.equal((await bridge('otp',pi.token)).status,400);assert.equal((await read('version:'+pc.id+':1')).signatures.length,0);
 const exported=await db.prepare('SELECT id,kind,data FROM records ORDER BY id').all();
 const backup={format:'radioadmin-backup',version:1,records:exported.results.map(row=>({...row,data:JSON.parse(row.data)}))};
 const restored=await rehearseBackup(backup);assert.equal(restored.records,backup.records.length);assert.ok(restored.versions>=3);
 }finally{await mf.dispose();}
});
