export const script=String.raw`
const $=id=>document.getElementById(id);
const token=new URLSearchParams(location.hash.slice(1)).get('token');
let current,blobUrl='',busy=false;
function status(message,error=false){$('status').textContent=message;$('status').className=error?'error':'';}
async function api(op,extra={}){const r=await fetch('/api/signature',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op,token,...extra})});const value=await r.json();if(!r.ok)throw Error(value.error||'Não foi possível concluir.');return value;}
function controls(){const blocked=busy||!current||current.used||!current.whatsappConfigured;$('otp').disabled=blocked;$('sign').disabled=blocked;}
async function documentPdf(){const value=await api('document');const bytes=Uint8Array.from(atob(value.pdf),c=>c.charCodeAt(0));const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');if(digest!==value.hash)throw Error('Documento não passou na verificação de integridade.');if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));$('download').href=blobUrl;$('download').download=value.filename;$('download').textContent=current.completed?'Baixar contrato concluído':'Baixar documento para leitura';
 try{const pdfjs=await import('/pdfjs/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/pdfjs/pdf.worker.mjs';const task=pdfjs.getDocument({data:bytes,standardFontDataUrl:'/pdfjs/standard_fonts/',isEvalSupported:false,useWasm:false}),pdfDocument=await task.promise;$('pdf').replaceChildren();for(let number=1;number<=pdfDocument.numPages;number++){const page=await pdfDocument.getPage(number),viewport=page.getViewport({scale:Math.min(1.5,($('pdf').clientWidth-2)/page.getViewport({scale:1}).width)}),canvas=window.document.createElement('canvas'),ratio=window.devicePixelRatio||1;canvas.width=Math.floor(viewport.width*ratio);canvas.height=Math.floor(viewport.height*ratio);canvas.style.width='100%';canvas.style.height='auto';canvas.setAttribute('aria-label','Página '+number+' do contrato');$('pdf').append(canvas);await page.render({canvas,canvasContext:canvas.getContext('2d'),viewport,transform:ratio!==1?[ratio,0,0,ratio,0,0]:null}).promise;}await task.destroy();}catch(error){console.warn('Leitor de PDF indisponível',error.message);$('pdf').textContent='Não foi possível exibir a prévia. Baixe o PDF para ler o contrato antes de assinar.';}
}
async function refresh(){try{const previous=current;current=await api('view');$('content').hidden=false;$('title').textContent=current.title+' | Versão '+current.number;$('role').textContent=current.signerRole==='client'?'Assinatura do cliente':'Assinatura do locutor/agente';$('recipient').textContent='Código enviado exclusivamente a '+current.phoneMasked;$('consentText').textContent=current.consentText;if(!previous)$('name').value=current.signerName;const s=current.summary;$('summary').replaceChildren();for(const pair of [['Emissora',current.station],['Anunciante',s.client],['Valor',Number(s.amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})],['Período',s.start+' a '+s.end],['Inserções',s.spots+' de '+s.duration+'s'],['Programa',s.program]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=pair[0];dd.textContent=pair[1];$('summary').append(dt,dd);}$('versionHash').textContent='Dados SHA-256: '+current.versionHash;$('documentHash').textContent='PDF SHA-256: '+(current.finalHash||current.documentHash);$('form').hidden=current.used;$('evidence').replaceChildren();for(const evidence of current.signatures){const p=document.createElement('p');p.textContent=evidence.name+' | '+new Date(evidence.date).toLocaleString('pt-BR');const code=document.createElement('code');code.textContent='Registro SHA-256: '+evidence.hash;$('evidence').append(p,code);}status(current.completed?'Contrato confirmado pela OPEC. PDF concluído disponível.':current.used?'Sua assinatura foi registrada. Aguardando as próximas etapas.':!current.whatsappConfigured?'A emissora ainda não conectou o WhatsApp oficial. A assinatura está indisponível.':'Leia o documento e confirme esta versão. Link válido até '+new Date(current.expiresAt).toLocaleString('pt-BR'));controls();if(!previous||previous.completed!==current.completed)await documentPdf();}catch(e){controls();status(e.message,true);}}
$('otp').addEventListener('click',async()=>{busy=true;controls();try{await api('otp');status('Código enviado ao WhatsApp cadastrado. Validade: 5 minutos.');}catch(e){status(e.message,true);}finally{busy=false;controls();}});
$('form').addEventListener('submit',async event=>{event.preventDefault();if(busy||!current)return;busy=true;controls();try{await api('sign',{name:$('name').value,document:$('document').value,code:$('code').value,consent:$('consent').checked,versionHash:current.versionHash,documentHash:current.documentHash});await refresh();}catch(e){status(e.message,true);}finally{busy=false;controls();}});
if(!/^[a-f0-9]{64}$/.test(token||'')){status('Abra o link individual enviado pela emissora. Não é necessário criar uma conta.');controls();}else{refresh();setInterval(()=>{if(!busy&&current&&current.used&&!current.completed)refresh();},20000);}
`;
